management.endpoints.web.exposure.include: hawtio,jolokia
hawtio.authenticationEnabled: false

activemq:
  broker.url: "tcp://0.0.0.0:61616"

spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2"
      settings.trace: false
      settings.web-allow-others: false

priceCache:
  systemConfig:
    jtaTransactionTimeoutMillis: 1000
    camelGracefulShutdownLimitSeconds: 1
  retention:
    daysValid: 30
    cron: 0 0/2 * * * ?
  jms:
    queues:
      vendorPrices: "vendorPrices"
      dlq: "dlq"
    endpoints:
      genericVendorQueue: "activemq:${priceCache.jms.queues.vendorPrices}"
      dlq: "activemq:${priceCache.jms.queues.dlq}"