INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1001, 'VALID', 1.1, DATEADD(day, -29, CURRENT_TIMESTAMP()), 'HL');

INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1002, 'OLD', 1.1, DATEADD(day, -31, CURRENT_TIMESTAMP()), 'HL');

