INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1001, 'AMZN', 1.1, CURRENT_TIMESTAMP(), 'HL');

INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1002, 'AAPL', 1.2, CURRENT_TIMESTAMP(), 'HL');

INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1003, 'AMZN', 2.1, CURRENT_TIMESTAMP(), 'BBG');

INSERT INTO INSTRUMENT_PRICES (ID, INSTRUMENT_ID, PRICE, PRICE_TIMESTAMP, VENDOR_ID)
    VALUES (1004, 'AAPL', 2.2, CURRENT_TIMESTAMP(), 'BBG');

